### ISSUE TITLE
Nodejs开发指南书中的一个小bugs ?

### ISSUE THREAD

**Issue by wagnlinzh** [BYVoid/microblog#9]
你好,最近在看您的书,首先 感谢您的书,写得非常通俗易懂, 很适合入门,再次感谢(^_^)

在阅读过程中,发现了有个地方和我所学OS基础好像有点出入, 疑似小bugs.
## 

书的第三章 3.2 小节 异步式 I/O 与事件式编程 ,31页

> 单线程事件驱动的异步式 I/O 比传统的多线程阻塞式 I/O 究竟好在哪里呢？简而言之， 异步式 I/O 就是少了多线程的开销。对操作系统来说，创建一个线程的代价是十分昂贵的， 需要给它分配内存、列入调度，同时在线程切换的时候还要执行内存换页，CPU 的缓存被 清空，切换回来的时候还要重新从内存中读取信息，破坏了数据的局部性.

我觉得 内存换页这种事情不是只有在不同进程的线程间进行切换时才会发生吗? 如果是相同进程的不同线程之间的切换时应该是不需要进行换页的吧?

**Comment by BYVoid** [comment]
根據情況，即使在同一進程，也是可能是需要換頁的。

**Comment by wagnlinzh** [comment]
@BYVoid 哦哦,谢谢 (^_^)
